import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { commentMetadata } from './comment-nodes.ts'
import { harnessRoot } from './manifest.ts'
import { fixtures } from './registry.ts'
import { adaptTreeSitter } from './tree-sitter.ts'
import type { CommentRange } from './tree-sitter.ts'
import type { Fixture } from './types.ts'

export interface CommentMetadata {
  readonly grammarRevision: string
  readonly parserSourceSha256: string
  readonly cliVersion: string
  readonly entries: readonly {
    readonly sourceSha256: string
    readonly comments: readonly CommentRange[]
  }[]
}

export function fixtureComments(fixture: Fixture, source: string, metadata: CommentMetadata = commentMetadata): readonly CommentRange[] {
  const sha256 = createHash('sha256').update(source, 'utf8').digest('hex')
  const entry = metadata.entries.find(entry => entry.sourceSha256 === fixture.sha256)
  if (!entry || sha256 !== entry.sourceSha256) throw new Error(`stale comment-node source hash for ${fixture.id}`)
  if (fixture.provenance.some(origin => origin.revision !== metadata.grammarRevision)) throw new Error('comment-node grammar revision mismatch')
  return entry.comments
}

function object(value: unknown): Record<string, unknown> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) throw new Error('comment metadata requires an object')
  return value as Record<string, unknown>
}

export function commentMetadataSource(input: unknown): string {
  const value = object(input)
  if (value.grammarRevision !== commentMetadata.grammarRevision || value.parserSourceSha256 !== commentMetadata.parserSourceSha256 ||
    typeof value.cliVersion !== 'string' || value.cliVersion.length === 0 || !Array.isArray(value.entries)) {
    throw new Error('comment metadata requires the pinned grammar/parser identity and extraction CLI version')
  }
  const entries = value.entries.map((item: unknown) => {
    const entry = object(item)
    if (typeof entry.sourceSha256 !== 'string' || !/^[0-9a-f]{64}$/.test(entry.sourceSha256) || !Array.isArray(entry.comments)) {
      throw new Error('comment metadata requires source hashes and parser comment ranges')
    }
    const comments = entry.comments.map((item: unknown) => {
      const node = object(item)
      if (typeof node.from !== 'number' || typeof node.to !== 'number') throw new Error('comment node requires UTF-16 offsets')
      return { from: node.from, to: node.to }
    })
    return { sourceSha256: entry.sourceSha256, comments }
  }).sort((a, b) => a.sourceSha256.localeCompare(b.sourceSha256, 'en'))
  const selected = fixtures.filter(fixture => fixture.family === 'tree-sitter-highlight')
  if (new Set(entries.map(entry => entry.sourceSha256)).size !== entries.length || entries.length !== selected.length) {
    throw new Error('comment metadata must contain every selected source exactly once')
  }
  const metadata: CommentMetadata = {
    grammarRevision: value.grammarRevision as string, parserSourceSha256: value.parserSourceSha256 as string,
    cliVersion: value.cliVersion, entries,
  }
  for (const fixture of selected) {
    const source = readFileSync(new URL(fixture.path, harnessRoot), 'utf8')
    const comments = fixtureComments(fixture, source, metadata)
    let end = 0
    for (const node of comments) {
      if (node.from < end || !source.slice(node.from, node.to).startsWith('//')) throw new Error('comment ranges must be ordered JavaScript line-comment nodes')
      end = node.to
    }
    adaptTreeSitter(source, fixture.id, fixture.path, comments)
  }
  return `// Generated by npm run fixtures:comments from parser-supplied UTF-16 nodes.\nimport type { CommentMetadata } from './comments.ts'\n\nexport const commentMetadata: CommentMetadata = ${JSON.stringify(metadata, null, 2)}\n`
}
