// Generated by npm run fixtures:comments from parser-supplied UTF-16 nodes.
import type { CommentMetadata } from './comments.ts'

export const commentMetadata: CommentMetadata = {
  "grammarRevision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
  "parserSourceSha256": "67209ca7ef6e1a4f74e29e48b5928455f892fe1821a3960fbcd62f4e972f7384",
  "cliVersion": "tree-sitter 0.26.9",
  "entries": [
    {
      "sourceSha256": "04108b8647ec48d87719c52df9795d861229983ad8a6def40821e50ed1d29f6e",
      "comments": [
        {
          "from": 56,
          "to": 69
        },
        {
          "from": 70,
          "to": 95
        },
        {
          "from": 96,
          "to": 138
        }
      ]
    },
    {
      "sourceSha256": "06a53d5fd7265258e58d489b016d3766caf3c4e2fbf3b9891c7f3428f486dcc6",
      "comments": [
        {
          "from": 13,
          "to": 27
        },
        {
          "from": 52,
          "to": 66
        },
        {
          "from": 86,
          "to": 100
        },
        {
          "from": 126,
          "to": 140
        },
        {
          "from": 158,
          "to": 175
        },
        {
          "from": 203,
          "to": 227
        },
        {
          "from": 261,
          "to": 285
        },
        {
          "from": 308,
          "to": 332
        },
        {
          "from": 351,
          "to": 368
        },
        {
          "from": 409,
          "to": 427
        },
        {
          "from": 447,
          "to": 467
        },
        {
          "from": 503,
          "to": 515
        },
        {
          "from": 518,
          "to": 539
        },
        {
          "from": 550,
          "to": 564
        },
        {
          "from": 578,
          "to": 602
        }
      ]
    },
    {
      "sourceSha256": "4808ef48df87bb8b929a52d91bcc87c125aaa117535612efa90ea94116cf01ec",
      "comments": [
        {
          "from": 11,
          "to": 30
        },
        {
          "from": 45,
          "to": 62
        },
        {
          "from": 79,
          "to": 95
        },
        {
          "from": 117,
          "to": 135
        },
        {
          "from": 177,
          "to": 199
        },
        {
          "from": 202,
          "to": 246
        },
        {
          "from": 305,
          "to": 319
        },
        {
          "from": 324,
          "to": 353
        },
        {
          "from": 394,
          "to": 415
        },
        {
          "from": 420,
          "to": 444
        },
        {
          "from": 449,
          "to": 480
        },
        {
          "from": 485,
          "to": 531
        },
        {
          "from": 572,
          "to": 593
        },
        {
          "from": 596,
          "to": 628
        },
        {
          "from": 631,
          "to": 672
        },
        {
          "from": 675,
          "to": 721
        },
        {
          "from": 757,
          "to": 778
        },
        {
          "from": 779,
          "to": 811
        },
        {
          "from": 812,
          "to": 843
        },
        {
          "from": 844,
          "to": 880
        },
        {
          "from": 921,
          "to": 943
        },
        {
          "from": 946,
          "to": 983
        },
        {
          "from": 986,
          "to": 1033
        },
        {
          "from": 1069,
          "to": 1092
        },
        {
          "from": 1095,
          "to": 1133
        },
        {
          "from": 1136,
          "to": 1181
        }
      ]
    },
    {
      "sourceSha256": "9a66c7a248abc299463167ace12e99ad0e3e1cab94cda4b1a9604d08ec42c451",
      "comments": [
        {
          "from": 17,
          "to": 30
        },
        {
          "from": 31,
          "to": 47
        },
        {
          "from": 80,
          "to": 93
        },
        {
          "from": 94,
          "to": 110
        },
        {
          "from": 111,
          "to": 140
        },
        {
          "from": 150,
          "to": 163
        },
        {
          "from": 164,
          "to": 180
        }
      ]
    },
    {
      "sourceSha256": "d52bc9ad2005e16422027a5c3ff81130cff1ce6ea8427cbba12e92e151044ae1",
      "comments": [
        {
          "from": 19,
          "to": 33
        },
        {
          "from": 34,
          "to": 50
        },
        {
          "from": 51,
          "to": 70
        },
        {
          "from": 71,
          "to": 95
        }
      ]
    }
  ]
}
