// Generated by npm run fixtures:update.
import type { Fixture, FixtureArtifact } from './types.ts'

export const fixtures: readonly Fixture[] = [
  {
    "id": "textmate-grammars-themes/samples/javascript.sample",
    "family": "textmate-grammars-themes",
    "languageId": "javascript",
    "path": "fixtures/textmate-grammars-themes/samples/javascript.sample",
    "sha256": "fff0add0e2876252ce6334a07257edc8251771548cad5b5362d2f20338e7b8b1",
    "lane": "catalog-smoke",
    "provenance": [
      {
        "sourceSetId": "catalog-samples",
        "repositoryId": "catalog",
        "revision": "37edd1b26f18838050661d912334aba0ca7f4931",
        "upstreamPath": "samples/javascript.sample",
        "manifestFileId": "catalog:samples/javascript.sample",
        "licenses": [
          "catalog-mit"
        ],
        "grammar": {
          "id": "catalog-javascript",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": null,
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": null,
          "productGrammarSha256": "a2108c805865c3a1d4941b30c97bdb68b23bebd6fd22c7656d2925527cc463fb",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development"
  },
  {
    "id": "textmate-grammars-themes/samples/typescript.sample",
    "family": "textmate-grammars-themes",
    "languageId": "typescript",
    "path": "fixtures/textmate-grammars-themes/samples/typescript.sample",
    "sha256": "18669770e176f60b535dead9ba0236419f2141678618a1b0b6e7e1f127b781c5",
    "lane": "catalog-smoke",
    "provenance": [
      {
        "sourceSetId": "catalog-samples",
        "repositoryId": "catalog",
        "revision": "37edd1b26f18838050661d912334aba0ca7f4931",
        "upstreamPath": "samples/typescript.sample",
        "manifestFileId": "catalog:samples/typescript.sample",
        "licenses": [
          "catalog-mit"
        ],
        "grammar": {
          "id": "catalog-typescript",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": null,
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": null,
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development"
  },
  {
    "id": "tree-sitter-highlight/test/highlight/functions.js",
    "family": "tree-sitter-highlight",
    "languageId": "javascript",
    "path": "fixtures/tree-sitter-highlight/test/highlight/functions.js",
    "sha256": "06a53d5fd7265258e58d489b016d3766caf3c4e2fbf3b9891c7f3428f486dcc6",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "tree-sitter-highlight",
        "repositoryId": "tree-sitter-javascript",
        "revision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
        "upstreamPath": "test/highlight/functions.js",
        "manifestFileId": "tree-sitter-javascript:test/highlight/functions.js",
        "licenses": [
          "tree-sitter-javascript-mit"
        ],
        "grammar": {
          "id": "tree-sitter-javascript-annotated",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": null,
          "productGrammarSha256": null,
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development"
  },
  {
    "id": "tree-sitter-highlight/test/highlight/imports.js",
    "family": "tree-sitter-highlight",
    "languageId": "javascript",
    "path": "fixtures/tree-sitter-highlight/test/highlight/imports.js",
    "sha256": "04108b8647ec48d87719c52df9795d861229983ad8a6def40821e50ed1d29f6e",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "tree-sitter-highlight",
        "repositoryId": "tree-sitter-javascript",
        "revision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
        "upstreamPath": "test/highlight/imports.js",
        "manifestFileId": "tree-sitter-javascript:test/highlight/imports.js",
        "licenses": [
          "tree-sitter-javascript-mit"
        ],
        "grammar": {
          "id": "tree-sitter-javascript-annotated",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": null,
          "productGrammarSha256": null,
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development"
  },
  {
    "id": "tree-sitter-highlight/test/highlight/injection.js",
    "family": "tree-sitter-highlight",
    "languageId": "javascript",
    "path": "fixtures/tree-sitter-highlight/test/highlight/injection.js",
    "sha256": "d52bc9ad2005e16422027a5c3ff81130cff1ce6ea8427cbba12e92e151044ae1",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "tree-sitter-highlight",
        "repositoryId": "tree-sitter-javascript",
        "revision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
        "upstreamPath": "test/highlight/injection.js",
        "manifestFileId": "tree-sitter-javascript:test/highlight/injection.js",
        "licenses": [
          "tree-sitter-javascript-mit"
        ],
        "grammar": {
          "id": "tree-sitter-javascript-annotated",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": null,
          "productGrammarSha256": null,
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development"
  },
  {
    "id": "tree-sitter-highlight/test/highlight/keywords.js",
    "family": "tree-sitter-highlight",
    "languageId": "javascript",
    "path": "fixtures/tree-sitter-highlight/test/highlight/keywords.js",
    "sha256": "9a66c7a248abc299463167ace12e99ad0e3e1cab94cda4b1a9604d08ec42c451",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "tree-sitter-highlight",
        "repositoryId": "tree-sitter-javascript",
        "revision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
        "upstreamPath": "test/highlight/keywords.js",
        "manifestFileId": "tree-sitter-javascript:test/highlight/keywords.js",
        "licenses": [
          "tree-sitter-javascript-mit"
        ],
        "grammar": {
          "id": "tree-sitter-javascript-annotated",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": null,
          "productGrammarSha256": null,
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development"
  },
  {
    "id": "tree-sitter-highlight/test/highlight/variables.js",
    "family": "tree-sitter-highlight",
    "languageId": "javascript",
    "path": "fixtures/tree-sitter-highlight/test/highlight/variables.js",
    "sha256": "4808ef48df87bb8b929a52d91bcc87c125aaa117535612efa90ea94116cf01ec",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "tree-sitter-highlight",
        "repositoryId": "tree-sitter-javascript",
        "revision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
        "upstreamPath": "test/highlight/variables.js",
        "manifestFileId": "tree-sitter-javascript:test/highlight/variables.js",
        "licenses": [
          "tree-sitter-javascript-mit"
        ],
        "grammar": {
          "id": "tree-sitter-javascript-annotated",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": null,
          "productGrammarSha256": null,
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development"
  },
  {
    "id": "typescript-tmlanguage/tests/cases/AsConstSatisfies.ts",
    "family": "typescript-tmlanguage",
    "languageId": "typescript",
    "path": "fixtures/typescript-tmlanguage/tests/cases/AsConstSatisfies.ts",
    "sha256": "d3043db40b618696d156fd5c17542762f95371a217b3f253b70efe26975c2f33",
    "lane": "language-regression",
    "provenance": [
      {
        "sourceSetId": "typescript-tmlanguage-cases",
        "repositoryId": "typescript-tmlanguage",
        "revision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
        "upstreamPath": "tests/cases/AsConstSatisfies.ts",
        "manifestFileId": "typescript-tmlanguage:tests/cases/AsConstSatisfies.ts",
        "licenses": [
          "typescript-mit"
        ],
        "grammar": {
          "id": "typescript-maintainer-ts",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": "5112e8f1a32325575e32d371cd4f1b8c4831f4b416147fd80e174b0fa7467566",
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development"
  },
  {
    "id": "typescript-tmlanguage/tests/cases/autoAccessor.ts",
    "family": "typescript-tmlanguage",
    "languageId": "typescript",
    "path": "fixtures/typescript-tmlanguage/tests/cases/autoAccessor.ts",
    "sha256": "d600d45bb9f7b9c915dbe2a396b19f4e5d8e8598e335a42423f2af00263f37e8",
    "lane": "language-regression",
    "provenance": [
      {
        "sourceSetId": "typescript-tmlanguage-cases",
        "repositoryId": "typescript-tmlanguage",
        "revision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
        "upstreamPath": "tests/cases/autoAccessor.ts",
        "manifestFileId": "typescript-tmlanguage:tests/cases/autoAccessor.ts",
        "licenses": [
          "typescript-mit"
        ],
        "grammar": {
          "id": "typescript-maintainer-ts",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": "5112e8f1a32325575e32d371cd4f1b8c4831f4b416147fd80e174b0fa7467566",
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development"
  },
  {
    "id": "typescript-tmlanguage/tests/cases/awaitUsing.ts",
    "family": "typescript-tmlanguage",
    "languageId": "typescript",
    "path": "fixtures/typescript-tmlanguage/tests/cases/awaitUsing.ts",
    "sha256": "c5cde4b5312fd7f765b9632a1a9e910002daf35a3347f73d1b19638688fa0572",
    "lane": "language-regression",
    "provenance": [
      {
        "sourceSetId": "typescript-tmlanguage-cases",
        "repositoryId": "typescript-tmlanguage",
        "revision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
        "upstreamPath": "tests/cases/awaitUsing.ts",
        "manifestFileId": "typescript-tmlanguage:tests/cases/awaitUsing.ts",
        "licenses": [
          "typescript-mit"
        ],
        "grammar": {
          "id": "typescript-maintainer-ts",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": "5112e8f1a32325575e32d371cd4f1b8c4831f4b416147fd80e174b0fa7467566",
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development"
  },
  {
    "id": "typescript-tmlanguage/tests/cases/constTypeParameter.ts",
    "family": "typescript-tmlanguage",
    "languageId": "typescript",
    "path": "fixtures/typescript-tmlanguage/tests/cases/constTypeParameter.ts",
    "sha256": "60e7a09ae8399bd4b54e11db5a8804bb52a1d9a2b061e4c0da4179ffb10248b4",
    "lane": "language-regression",
    "provenance": [
      {
        "sourceSetId": "typescript-tmlanguage-cases",
        "repositoryId": "typescript-tmlanguage",
        "revision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
        "upstreamPath": "tests/cases/constTypeParameter.ts",
        "manifestFileId": "typescript-tmlanguage:tests/cases/constTypeParameter.ts",
        "licenses": [
          "typescript-mit"
        ],
        "grammar": {
          "id": "typescript-maintainer-ts",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": "5112e8f1a32325575e32d371cd4f1b8c4831f4b416147fd80e174b0fa7467566",
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development"
  },
  {
    "id": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test-brackets.tsx",
    "family": "vscode-colorize",
    "languageId": "tsx",
    "path": "fixtures/vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test-brackets.tsx",
    "sha256": "2d33e00ba3c02b140644715a43770c0750fb1774ec31ee1d349eaa17f5518609",
    "lane": "language-regression",
    "provenance": [
      {
        "sourceSetId": "vscode-colorize-fixtures",
        "repositoryId": "vscode",
        "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
        "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-fixtures/test-brackets.tsx",
        "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-fixtures/test-brackets.tsx",
        "licenses": [
          "vscode-mit"
        ],
        "grammar": {
          "id": "vscode-source.tsx",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
          "inspectedGrammarSha256": "532fb887df3117e9f4eaf5d3ea1e850114fb6899fe3d3ddabedb153bec08b32a",
          "productGrammarSha256": "e04ffdb50f237b70ab8c27653681a72004617ece8a6d5ff6aba58eaae6082eae",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development"
  },
  {
    "id": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test-keywords.ts",
    "family": "vscode-colorize",
    "languageId": "typescript",
    "path": "fixtures/vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test-keywords.ts",
    "sha256": "491e4563c720e23b629f295fcea28dc589b557ece4595f2b5f4ae70011fab1f6",
    "lane": "language-regression",
    "provenance": [
      {
        "sourceSetId": "vscode-colorize-fixtures",
        "repositoryId": "vscode",
        "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
        "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-fixtures/test-keywords.ts",
        "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-fixtures/test-keywords.ts",
        "licenses": [
          "vscode-mit"
        ],
        "grammar": {
          "id": "vscode-source.ts",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
          "inspectedGrammarSha256": "4e92e0d7de560217d6c8d3236d85e6e17a5d77825b15729a230c761743122661",
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development"
  },
  {
    "id": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test-object-literals.ts",
    "family": "vscode-colorize",
    "languageId": "typescript",
    "path": "fixtures/vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test-object-literals.ts",
    "sha256": "276ecad82959d3fb8c77d19586a8f54e65b05093a5c3feb217278cf7f5f22355",
    "lane": "language-regression",
    "provenance": [
      {
        "sourceSetId": "vscode-colorize-fixtures",
        "repositoryId": "vscode",
        "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
        "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-fixtures/test-object-literals.ts",
        "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-fixtures/test-object-literals.ts",
        "licenses": [
          "vscode-mit"
        ],
        "grammar": {
          "id": "vscode-source.ts",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
          "inspectedGrammarSha256": "4e92e0d7de560217d6c8d3236d85e6e17a5d77825b15729a230c761743122661",
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development"
  },
  {
    "id": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test.js",
    "family": "vscode-colorize",
    "languageId": "javascript",
    "path": "fixtures/vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test.js",
    "sha256": "d86234cda3285c0d00e0e0326f5f4d29a768e7b91dd8ce255abcf251d5afc053",
    "lane": "language-regression",
    "provenance": [
      {
        "sourceSetId": "vscode-colorize-fixtures",
        "repositoryId": "vscode",
        "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
        "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-fixtures/test.js",
        "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-fixtures/test.js",
        "licenses": [
          "vscode-mit"
        ],
        "grammar": {
          "id": "vscode-source.js",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
          "inspectedGrammarSha256": "db6f17f15bc4f5e860a3b8fa6055a69720a53df845c8d5121cdc4f128c16291f",
          "productGrammarSha256": "a2108c805865c3a1d4941b30c97bdb68b23bebd6fd22c7656d2925527cc463fb",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development"
  },
  {
    "id": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test.json",
    "family": "vscode-colorize",
    "languageId": "json",
    "path": "fixtures/vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test.json",
    "sha256": "b2d531295f4856719d5eb1bf2f5fa42bc0ea8436b5687cde0ed19e504866c360",
    "lane": "language-regression",
    "provenance": [
      {
        "sourceSetId": "vscode-colorize-fixtures",
        "repositoryId": "vscode",
        "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
        "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-fixtures/test.json",
        "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-fixtures/test.json",
        "licenses": [
          "vscode-mit"
        ],
        "grammar": {
          "id": "vscode-source.json",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "inspectedUpstreamRevision": "9bd83f1c252b375e957203f21793316203f61f70",
          "inspectedGrammarSha256": "d7238f1cc9033993b9816b0945cab4bb8ea108de0399663c551f28f913e94c70",
          "productGrammarSha256": "9381fc3b1fd0bf3aad0dde03ca4a610fe4026b42173d33d4ae7b420ff24b5989",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development"
  }
]

export const fixtureArtifacts: readonly FixtureArtifact[] = [
  {
    "id": "textmate-grammars-themes/samples/javascript.sample",
    "family": "textmate-grammars-themes",
    "languageId": "javascript",
    "path": "fixtures/textmate-grammars-themes/samples/javascript.sample",
    "sha256": "fff0add0e2876252ce6334a07257edc8251771548cad5b5362d2f20338e7b8b1",
    "lane": "catalog-smoke",
    "provenance": [
      {
        "sourceSetId": "catalog-samples",
        "repositoryId": "catalog",
        "revision": "37edd1b26f18838050661d912334aba0ca7f4931",
        "upstreamPath": "samples/javascript.sample",
        "manifestFileId": "catalog:samples/javascript.sample",
        "licenses": [
          "catalog-mit"
        ],
        "grammar": {
          "id": "catalog-javascript",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": null,
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": null,
          "productGrammarSha256": "a2108c805865c3a1d4941b30c97bdb68b23bebd6fd22c7656d2925527cc463fb",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "source",
    "associations": [
      {
        "sourceFixtureId": "textmate-grammars-themes/samples/javascript.sample",
        "format": "source",
        "provenance": {
          "sourceSetId": "catalog-samples",
          "repositoryId": "catalog",
          "revision": "37edd1b26f18838050661d912334aba0ca7f4931",
          "upstreamPath": "samples/javascript.sample",
          "manifestFileId": "catalog:samples/javascript.sample",
          "licenses": [
            "catalog-mit"
          ],
          "grammar": {
            "id": "catalog-javascript",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": null,
            "inspectedUpstreamRevision": null,
            "inspectedGrammarSha256": null,
            "productGrammarSha256": "a2108c805865c3a1d4941b30c97bdb68b23bebd6fd22c7656d2925527cc463fb",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "textmate-grammars-themes/samples/typescript.sample",
    "family": "textmate-grammars-themes",
    "languageId": "typescript",
    "path": "fixtures/textmate-grammars-themes/samples/typescript.sample",
    "sha256": "18669770e176f60b535dead9ba0236419f2141678618a1b0b6e7e1f127b781c5",
    "lane": "catalog-smoke",
    "provenance": [
      {
        "sourceSetId": "catalog-samples",
        "repositoryId": "catalog",
        "revision": "37edd1b26f18838050661d912334aba0ca7f4931",
        "upstreamPath": "samples/typescript.sample",
        "manifestFileId": "catalog:samples/typescript.sample",
        "licenses": [
          "catalog-mit"
        ],
        "grammar": {
          "id": "catalog-typescript",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": null,
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": null,
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "source",
    "associations": [
      {
        "sourceFixtureId": "textmate-grammars-themes/samples/typescript.sample",
        "format": "source",
        "provenance": {
          "sourceSetId": "catalog-samples",
          "repositoryId": "catalog",
          "revision": "37edd1b26f18838050661d912334aba0ca7f4931",
          "upstreamPath": "samples/typescript.sample",
          "manifestFileId": "catalog:samples/typescript.sample",
          "licenses": [
            "catalog-mit"
          ],
          "grammar": {
            "id": "catalog-typescript",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": null,
            "inspectedUpstreamRevision": null,
            "inspectedGrammarSha256": null,
            "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "tree-sitter-highlight/test/highlight/functions.js",
    "family": "tree-sitter-highlight",
    "languageId": "javascript",
    "path": "fixtures/tree-sitter-highlight/test/highlight/functions.js",
    "sha256": "06a53d5fd7265258e58d489b016d3766caf3c4e2fbf3b9891c7f3428f486dcc6",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "tree-sitter-highlight",
        "repositoryId": "tree-sitter-javascript",
        "revision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
        "upstreamPath": "test/highlight/functions.js",
        "manifestFileId": "tree-sitter-javascript:test/highlight/functions.js",
        "licenses": [
          "tree-sitter-javascript-mit"
        ],
        "grammar": {
          "id": "tree-sitter-javascript-annotated",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": null,
          "productGrammarSha256": null,
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "tree-sitter-highlight",
    "associations": [
      {
        "sourceFixtureId": "tree-sitter-highlight/test/highlight/functions.js",
        "format": "tree-sitter-highlight",
        "provenance": {
          "sourceSetId": "tree-sitter-highlight",
          "repositoryId": "tree-sitter-javascript",
          "revision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
          "upstreamPath": "test/highlight/functions.js",
          "manifestFileId": "tree-sitter-javascript:test/highlight/functions.js",
          "licenses": [
            "tree-sitter-javascript-mit"
          ],
          "grammar": {
            "id": "tree-sitter-javascript-annotated",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
            "inspectedUpstreamRevision": null,
            "inspectedGrammarSha256": null,
            "productGrammarSha256": null,
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "tree-sitter-highlight/test/highlight/imports.js",
    "family": "tree-sitter-highlight",
    "languageId": "javascript",
    "path": "fixtures/tree-sitter-highlight/test/highlight/imports.js",
    "sha256": "04108b8647ec48d87719c52df9795d861229983ad8a6def40821e50ed1d29f6e",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "tree-sitter-highlight",
        "repositoryId": "tree-sitter-javascript",
        "revision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
        "upstreamPath": "test/highlight/imports.js",
        "manifestFileId": "tree-sitter-javascript:test/highlight/imports.js",
        "licenses": [
          "tree-sitter-javascript-mit"
        ],
        "grammar": {
          "id": "tree-sitter-javascript-annotated",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": null,
          "productGrammarSha256": null,
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "tree-sitter-highlight",
    "associations": [
      {
        "sourceFixtureId": "tree-sitter-highlight/test/highlight/imports.js",
        "format": "tree-sitter-highlight",
        "provenance": {
          "sourceSetId": "tree-sitter-highlight",
          "repositoryId": "tree-sitter-javascript",
          "revision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
          "upstreamPath": "test/highlight/imports.js",
          "manifestFileId": "tree-sitter-javascript:test/highlight/imports.js",
          "licenses": [
            "tree-sitter-javascript-mit"
          ],
          "grammar": {
            "id": "tree-sitter-javascript-annotated",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
            "inspectedUpstreamRevision": null,
            "inspectedGrammarSha256": null,
            "productGrammarSha256": null,
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "tree-sitter-highlight/test/highlight/injection.js",
    "family": "tree-sitter-highlight",
    "languageId": "javascript",
    "path": "fixtures/tree-sitter-highlight/test/highlight/injection.js",
    "sha256": "d52bc9ad2005e16422027a5c3ff81130cff1ce6ea8427cbba12e92e151044ae1",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "tree-sitter-highlight",
        "repositoryId": "tree-sitter-javascript",
        "revision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
        "upstreamPath": "test/highlight/injection.js",
        "manifestFileId": "tree-sitter-javascript:test/highlight/injection.js",
        "licenses": [
          "tree-sitter-javascript-mit"
        ],
        "grammar": {
          "id": "tree-sitter-javascript-annotated",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": null,
          "productGrammarSha256": null,
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "tree-sitter-highlight",
    "associations": [
      {
        "sourceFixtureId": "tree-sitter-highlight/test/highlight/injection.js",
        "format": "tree-sitter-highlight",
        "provenance": {
          "sourceSetId": "tree-sitter-highlight",
          "repositoryId": "tree-sitter-javascript",
          "revision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
          "upstreamPath": "test/highlight/injection.js",
          "manifestFileId": "tree-sitter-javascript:test/highlight/injection.js",
          "licenses": [
            "tree-sitter-javascript-mit"
          ],
          "grammar": {
            "id": "tree-sitter-javascript-annotated",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
            "inspectedUpstreamRevision": null,
            "inspectedGrammarSha256": null,
            "productGrammarSha256": null,
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "tree-sitter-highlight/test/highlight/keywords.js",
    "family": "tree-sitter-highlight",
    "languageId": "javascript",
    "path": "fixtures/tree-sitter-highlight/test/highlight/keywords.js",
    "sha256": "9a66c7a248abc299463167ace12e99ad0e3e1cab94cda4b1a9604d08ec42c451",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "tree-sitter-highlight",
        "repositoryId": "tree-sitter-javascript",
        "revision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
        "upstreamPath": "test/highlight/keywords.js",
        "manifestFileId": "tree-sitter-javascript:test/highlight/keywords.js",
        "licenses": [
          "tree-sitter-javascript-mit"
        ],
        "grammar": {
          "id": "tree-sitter-javascript-annotated",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": null,
          "productGrammarSha256": null,
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "tree-sitter-highlight",
    "associations": [
      {
        "sourceFixtureId": "tree-sitter-highlight/test/highlight/keywords.js",
        "format": "tree-sitter-highlight",
        "provenance": {
          "sourceSetId": "tree-sitter-highlight",
          "repositoryId": "tree-sitter-javascript",
          "revision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
          "upstreamPath": "test/highlight/keywords.js",
          "manifestFileId": "tree-sitter-javascript:test/highlight/keywords.js",
          "licenses": [
            "tree-sitter-javascript-mit"
          ],
          "grammar": {
            "id": "tree-sitter-javascript-annotated",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
            "inspectedUpstreamRevision": null,
            "inspectedGrammarSha256": null,
            "productGrammarSha256": null,
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "tree-sitter-highlight/test/highlight/variables.js",
    "family": "tree-sitter-highlight",
    "languageId": "javascript",
    "path": "fixtures/tree-sitter-highlight/test/highlight/variables.js",
    "sha256": "4808ef48df87bb8b929a52d91bcc87c125aaa117535612efa90ea94116cf01ec",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "tree-sitter-highlight",
        "repositoryId": "tree-sitter-javascript",
        "revision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
        "upstreamPath": "test/highlight/variables.js",
        "manifestFileId": "tree-sitter-javascript:test/highlight/variables.js",
        "licenses": [
          "tree-sitter-javascript-mit"
        ],
        "grammar": {
          "id": "tree-sitter-javascript-annotated",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": null,
          "productGrammarSha256": null,
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "tree-sitter-highlight",
    "associations": [
      {
        "sourceFixtureId": "tree-sitter-highlight/test/highlight/variables.js",
        "format": "tree-sitter-highlight",
        "provenance": {
          "sourceSetId": "tree-sitter-highlight",
          "repositoryId": "tree-sitter-javascript",
          "revision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
          "upstreamPath": "test/highlight/variables.js",
          "manifestFileId": "tree-sitter-javascript:test/highlight/variables.js",
          "licenses": [
            "tree-sitter-javascript-mit"
          ],
          "grammar": {
            "id": "tree-sitter-javascript-annotated",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "44c892e0be055ac465d5eeddae6d3e194424e7de",
            "inspectedUpstreamRevision": null,
            "inspectedGrammarSha256": null,
            "productGrammarSha256": null,
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "typescript-tmlanguage/tests/baselines/AsConstSatisfies.baseline.txt",
    "family": "typescript-tmlanguage",
    "languageId": "typescript",
    "path": "fixtures/typescript-tmlanguage/tests/baselines/AsConstSatisfies.baseline.txt",
    "sha256": "9359c69c82f7e60855d02a3a518d6021554afac199b694c7afd382f4aea921c0",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "typescript-tmlanguage-baselines",
        "repositoryId": "typescript-tmlanguage",
        "revision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
        "upstreamPath": "tests/baselines/AsConstSatisfies.baseline.txt",
        "manifestFileId": "typescript-tmlanguage:tests/baselines/AsConstSatisfies.baseline.txt",
        "licenses": [
          "typescript-mit"
        ],
        "grammar": {
          "id": "typescript-maintainer-ts",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": "5112e8f1a32325575e32d371cd4f1b8c4831f4b416147fd80e174b0fa7467566",
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "typescript-baseline",
    "associations": [
      {
        "sourceFixtureId": "typescript-tmlanguage/tests/cases/AsConstSatisfies.ts",
        "format": "typescript-baseline",
        "provenance": {
          "sourceSetId": "typescript-tmlanguage-baselines",
          "repositoryId": "typescript-tmlanguage",
          "revision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
          "upstreamPath": "tests/baselines/AsConstSatisfies.baseline.txt",
          "manifestFileId": "typescript-tmlanguage:tests/baselines/AsConstSatisfies.baseline.txt",
          "licenses": [
            "typescript-mit"
          ],
          "grammar": {
            "id": "typescript-maintainer-ts",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
            "inspectedUpstreamRevision": null,
            "inspectedGrammarSha256": "5112e8f1a32325575e32d371cd4f1b8c4831f4b416147fd80e174b0fa7467566",
            "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "typescript-tmlanguage/tests/baselines/autoAccessor.baseline.txt",
    "family": "typescript-tmlanguage",
    "languageId": "typescript",
    "path": "fixtures/typescript-tmlanguage/tests/baselines/autoAccessor.baseline.txt",
    "sha256": "9fc779967c02034a66c43a33418e87415edcd39d767e24375c380485d92c2271",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "typescript-tmlanguage-baselines",
        "repositoryId": "typescript-tmlanguage",
        "revision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
        "upstreamPath": "tests/baselines/autoAccessor.baseline.txt",
        "manifestFileId": "typescript-tmlanguage:tests/baselines/autoAccessor.baseline.txt",
        "licenses": [
          "typescript-mit"
        ],
        "grammar": {
          "id": "typescript-maintainer-ts",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": "5112e8f1a32325575e32d371cd4f1b8c4831f4b416147fd80e174b0fa7467566",
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "typescript-baseline",
    "associations": [
      {
        "sourceFixtureId": "typescript-tmlanguage/tests/cases/autoAccessor.ts",
        "format": "typescript-baseline",
        "provenance": {
          "sourceSetId": "typescript-tmlanguage-baselines",
          "repositoryId": "typescript-tmlanguage",
          "revision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
          "upstreamPath": "tests/baselines/autoAccessor.baseline.txt",
          "manifestFileId": "typescript-tmlanguage:tests/baselines/autoAccessor.baseline.txt",
          "licenses": [
            "typescript-mit"
          ],
          "grammar": {
            "id": "typescript-maintainer-ts",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
            "inspectedUpstreamRevision": null,
            "inspectedGrammarSha256": "5112e8f1a32325575e32d371cd4f1b8c4831f4b416147fd80e174b0fa7467566",
            "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "typescript-tmlanguage/tests/baselines/awaitUsing.baseline.txt",
    "family": "typescript-tmlanguage",
    "languageId": "typescript",
    "path": "fixtures/typescript-tmlanguage/tests/baselines/awaitUsing.baseline.txt",
    "sha256": "d21f968903c131f64eb8d21f7a3b37dbb709d465d0ec6005505c3154e154fb52",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "typescript-tmlanguage-baselines",
        "repositoryId": "typescript-tmlanguage",
        "revision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
        "upstreamPath": "tests/baselines/awaitUsing.baseline.txt",
        "manifestFileId": "typescript-tmlanguage:tests/baselines/awaitUsing.baseline.txt",
        "licenses": [
          "typescript-mit"
        ],
        "grammar": {
          "id": "typescript-maintainer-ts",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": "5112e8f1a32325575e32d371cd4f1b8c4831f4b416147fd80e174b0fa7467566",
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "typescript-baseline",
    "associations": [
      {
        "sourceFixtureId": "typescript-tmlanguage/tests/cases/awaitUsing.ts",
        "format": "typescript-baseline",
        "provenance": {
          "sourceSetId": "typescript-tmlanguage-baselines",
          "repositoryId": "typescript-tmlanguage",
          "revision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
          "upstreamPath": "tests/baselines/awaitUsing.baseline.txt",
          "manifestFileId": "typescript-tmlanguage:tests/baselines/awaitUsing.baseline.txt",
          "licenses": [
            "typescript-mit"
          ],
          "grammar": {
            "id": "typescript-maintainer-ts",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
            "inspectedUpstreamRevision": null,
            "inspectedGrammarSha256": "5112e8f1a32325575e32d371cd4f1b8c4831f4b416147fd80e174b0fa7467566",
            "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "typescript-tmlanguage/tests/baselines/constTypeParameter.baseline.txt",
    "family": "typescript-tmlanguage",
    "languageId": "typescript",
    "path": "fixtures/typescript-tmlanguage/tests/baselines/constTypeParameter.baseline.txt",
    "sha256": "0016a5d2caa77ce358baa59f278d30bcaefa2a858d2f78d387c2c6b63c1439c2",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "typescript-tmlanguage-baselines",
        "repositoryId": "typescript-tmlanguage",
        "revision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
        "upstreamPath": "tests/baselines/constTypeParameter.baseline.txt",
        "manifestFileId": "typescript-tmlanguage:tests/baselines/constTypeParameter.baseline.txt",
        "licenses": [
          "typescript-mit"
        ],
        "grammar": {
          "id": "typescript-maintainer-ts",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": "5112e8f1a32325575e32d371cd4f1b8c4831f4b416147fd80e174b0fa7467566",
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "typescript-baseline",
    "associations": [
      {
        "sourceFixtureId": "typescript-tmlanguage/tests/cases/constTypeParameter.ts",
        "format": "typescript-baseline",
        "provenance": {
          "sourceSetId": "typescript-tmlanguage-baselines",
          "repositoryId": "typescript-tmlanguage",
          "revision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
          "upstreamPath": "tests/baselines/constTypeParameter.baseline.txt",
          "manifestFileId": "typescript-tmlanguage:tests/baselines/constTypeParameter.baseline.txt",
          "licenses": [
            "typescript-mit"
          ],
          "grammar": {
            "id": "typescript-maintainer-ts",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
            "inspectedUpstreamRevision": null,
            "inspectedGrammarSha256": "5112e8f1a32325575e32d371cd4f1b8c4831f4b416147fd80e174b0fa7467566",
            "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "typescript-tmlanguage/tests/cases/AsConstSatisfies.ts",
    "family": "typescript-tmlanguage",
    "languageId": "typescript",
    "path": "fixtures/typescript-tmlanguage/tests/cases/AsConstSatisfies.ts",
    "sha256": "d3043db40b618696d156fd5c17542762f95371a217b3f253b70efe26975c2f33",
    "lane": "language-regression",
    "provenance": [
      {
        "sourceSetId": "typescript-tmlanguage-cases",
        "repositoryId": "typescript-tmlanguage",
        "revision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
        "upstreamPath": "tests/cases/AsConstSatisfies.ts",
        "manifestFileId": "typescript-tmlanguage:tests/cases/AsConstSatisfies.ts",
        "licenses": [
          "typescript-mit"
        ],
        "grammar": {
          "id": "typescript-maintainer-ts",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": "5112e8f1a32325575e32d371cd4f1b8c4831f4b416147fd80e174b0fa7467566",
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "source",
    "associations": [
      {
        "sourceFixtureId": "typescript-tmlanguage/tests/cases/AsConstSatisfies.ts",
        "format": "source",
        "provenance": {
          "sourceSetId": "typescript-tmlanguage-cases",
          "repositoryId": "typescript-tmlanguage",
          "revision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
          "upstreamPath": "tests/cases/AsConstSatisfies.ts",
          "manifestFileId": "typescript-tmlanguage:tests/cases/AsConstSatisfies.ts",
          "licenses": [
            "typescript-mit"
          ],
          "grammar": {
            "id": "typescript-maintainer-ts",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
            "inspectedUpstreamRevision": null,
            "inspectedGrammarSha256": "5112e8f1a32325575e32d371cd4f1b8c4831f4b416147fd80e174b0fa7467566",
            "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "typescript-tmlanguage/tests/cases/autoAccessor.ts",
    "family": "typescript-tmlanguage",
    "languageId": "typescript",
    "path": "fixtures/typescript-tmlanguage/tests/cases/autoAccessor.ts",
    "sha256": "d600d45bb9f7b9c915dbe2a396b19f4e5d8e8598e335a42423f2af00263f37e8",
    "lane": "language-regression",
    "provenance": [
      {
        "sourceSetId": "typescript-tmlanguage-cases",
        "repositoryId": "typescript-tmlanguage",
        "revision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
        "upstreamPath": "tests/cases/autoAccessor.ts",
        "manifestFileId": "typescript-tmlanguage:tests/cases/autoAccessor.ts",
        "licenses": [
          "typescript-mit"
        ],
        "grammar": {
          "id": "typescript-maintainer-ts",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": "5112e8f1a32325575e32d371cd4f1b8c4831f4b416147fd80e174b0fa7467566",
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "source",
    "associations": [
      {
        "sourceFixtureId": "typescript-tmlanguage/tests/cases/autoAccessor.ts",
        "format": "source",
        "provenance": {
          "sourceSetId": "typescript-tmlanguage-cases",
          "repositoryId": "typescript-tmlanguage",
          "revision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
          "upstreamPath": "tests/cases/autoAccessor.ts",
          "manifestFileId": "typescript-tmlanguage:tests/cases/autoAccessor.ts",
          "licenses": [
            "typescript-mit"
          ],
          "grammar": {
            "id": "typescript-maintainer-ts",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
            "inspectedUpstreamRevision": null,
            "inspectedGrammarSha256": "5112e8f1a32325575e32d371cd4f1b8c4831f4b416147fd80e174b0fa7467566",
            "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "typescript-tmlanguage/tests/cases/awaitUsing.ts",
    "family": "typescript-tmlanguage",
    "languageId": "typescript",
    "path": "fixtures/typescript-tmlanguage/tests/cases/awaitUsing.ts",
    "sha256": "c5cde4b5312fd7f765b9632a1a9e910002daf35a3347f73d1b19638688fa0572",
    "lane": "language-regression",
    "provenance": [
      {
        "sourceSetId": "typescript-tmlanguage-cases",
        "repositoryId": "typescript-tmlanguage",
        "revision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
        "upstreamPath": "tests/cases/awaitUsing.ts",
        "manifestFileId": "typescript-tmlanguage:tests/cases/awaitUsing.ts",
        "licenses": [
          "typescript-mit"
        ],
        "grammar": {
          "id": "typescript-maintainer-ts",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": "5112e8f1a32325575e32d371cd4f1b8c4831f4b416147fd80e174b0fa7467566",
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "source",
    "associations": [
      {
        "sourceFixtureId": "typescript-tmlanguage/tests/cases/awaitUsing.ts",
        "format": "source",
        "provenance": {
          "sourceSetId": "typescript-tmlanguage-cases",
          "repositoryId": "typescript-tmlanguage",
          "revision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
          "upstreamPath": "tests/cases/awaitUsing.ts",
          "manifestFileId": "typescript-tmlanguage:tests/cases/awaitUsing.ts",
          "licenses": [
            "typescript-mit"
          ],
          "grammar": {
            "id": "typescript-maintainer-ts",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
            "inspectedUpstreamRevision": null,
            "inspectedGrammarSha256": "5112e8f1a32325575e32d371cd4f1b8c4831f4b416147fd80e174b0fa7467566",
            "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "typescript-tmlanguage/tests/cases/constTypeParameter.ts",
    "family": "typescript-tmlanguage",
    "languageId": "typescript",
    "path": "fixtures/typescript-tmlanguage/tests/cases/constTypeParameter.ts",
    "sha256": "60e7a09ae8399bd4b54e11db5a8804bb52a1d9a2b061e4c0da4179ffb10248b4",
    "lane": "language-regression",
    "provenance": [
      {
        "sourceSetId": "typescript-tmlanguage-cases",
        "repositoryId": "typescript-tmlanguage",
        "revision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
        "upstreamPath": "tests/cases/constTypeParameter.ts",
        "manifestFileId": "typescript-tmlanguage:tests/cases/constTypeParameter.ts",
        "licenses": [
          "typescript-mit"
        ],
        "grammar": {
          "id": "typescript-maintainer-ts",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
          "inspectedUpstreamRevision": null,
          "inspectedGrammarSha256": "5112e8f1a32325575e32d371cd4f1b8c4831f4b416147fd80e174b0fa7467566",
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "source",
    "associations": [
      {
        "sourceFixtureId": "typescript-tmlanguage/tests/cases/constTypeParameter.ts",
        "format": "source",
        "provenance": {
          "sourceSetId": "typescript-tmlanguage-cases",
          "repositoryId": "typescript-tmlanguage",
          "revision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
          "upstreamPath": "tests/cases/constTypeParameter.ts",
          "manifestFileId": "typescript-tmlanguage:tests/cases/constTypeParameter.ts",
          "licenses": [
            "typescript-mit"
          ],
          "grammar": {
            "id": "typescript-maintainer-ts",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "eeeb0dc4daa8793b8227bb3b34ddfc267c85fd81",
            "inspectedUpstreamRevision": null,
            "inspectedGrammarSha256": "5112e8f1a32325575e32d371cd4f1b8c4831f4b416147fd80e174b0fa7467566",
            "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test-brackets.tsx",
    "family": "vscode-colorize",
    "languageId": "tsx",
    "path": "fixtures/vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test-brackets.tsx",
    "sha256": "2d33e00ba3c02b140644715a43770c0750fb1774ec31ee1d349eaa17f5518609",
    "lane": "language-regression",
    "provenance": [
      {
        "sourceSetId": "vscode-colorize-fixtures",
        "repositoryId": "vscode",
        "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
        "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-fixtures/test-brackets.tsx",
        "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-fixtures/test-brackets.tsx",
        "licenses": [
          "vscode-mit"
        ],
        "grammar": {
          "id": "vscode-source.tsx",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
          "inspectedGrammarSha256": "532fb887df3117e9f4eaf5d3ea1e850114fb6899fe3d3ddabedb153bec08b32a",
          "productGrammarSha256": "e04ffdb50f237b70ab8c27653681a72004617ece8a6d5ff6aba58eaae6082eae",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "source",
    "associations": [
      {
        "sourceFixtureId": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test-brackets.tsx",
        "format": "source",
        "provenance": {
          "sourceSetId": "vscode-colorize-fixtures",
          "repositoryId": "vscode",
          "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-fixtures/test-brackets.tsx",
          "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-fixtures/test-brackets.tsx",
          "licenses": [
            "vscode-mit"
          ],
          "grammar": {
            "id": "vscode-source.tsx",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
            "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
            "inspectedGrammarSha256": "532fb887df3117e9f4eaf5d3ea1e850114fb6899fe3d3ddabedb153bec08b32a",
            "productGrammarSha256": "e04ffdb50f237b70ab8c27653681a72004617ece8a6d5ff6aba58eaae6082eae",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test-keywords.ts",
    "family": "vscode-colorize",
    "languageId": "typescript",
    "path": "fixtures/vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test-keywords.ts",
    "sha256": "491e4563c720e23b629f295fcea28dc589b557ece4595f2b5f4ae70011fab1f6",
    "lane": "language-regression",
    "provenance": [
      {
        "sourceSetId": "vscode-colorize-fixtures",
        "repositoryId": "vscode",
        "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
        "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-fixtures/test-keywords.ts",
        "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-fixtures/test-keywords.ts",
        "licenses": [
          "vscode-mit"
        ],
        "grammar": {
          "id": "vscode-source.ts",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
          "inspectedGrammarSha256": "4e92e0d7de560217d6c8d3236d85e6e17a5d77825b15729a230c761743122661",
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "source",
    "associations": [
      {
        "sourceFixtureId": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test-keywords.ts",
        "format": "source",
        "provenance": {
          "sourceSetId": "vscode-colorize-fixtures",
          "repositoryId": "vscode",
          "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-fixtures/test-keywords.ts",
          "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-fixtures/test-keywords.ts",
          "licenses": [
            "vscode-mit"
          ],
          "grammar": {
            "id": "vscode-source.ts",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
            "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
            "inspectedGrammarSha256": "4e92e0d7de560217d6c8d3236d85e6e17a5d77825b15729a230c761743122661",
            "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test-object-literals.ts",
    "family": "vscode-colorize",
    "languageId": "typescript",
    "path": "fixtures/vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test-object-literals.ts",
    "sha256": "276ecad82959d3fb8c77d19586a8f54e65b05093a5c3feb217278cf7f5f22355",
    "lane": "language-regression",
    "provenance": [
      {
        "sourceSetId": "vscode-colorize-fixtures",
        "repositoryId": "vscode",
        "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
        "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-fixtures/test-object-literals.ts",
        "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-fixtures/test-object-literals.ts",
        "licenses": [
          "vscode-mit"
        ],
        "grammar": {
          "id": "vscode-source.ts",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
          "inspectedGrammarSha256": "4e92e0d7de560217d6c8d3236d85e6e17a5d77825b15729a230c761743122661",
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "source",
    "associations": [
      {
        "sourceFixtureId": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test-object-literals.ts",
        "format": "source",
        "provenance": {
          "sourceSetId": "vscode-colorize-fixtures",
          "repositoryId": "vscode",
          "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-fixtures/test-object-literals.ts",
          "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-fixtures/test-object-literals.ts",
          "licenses": [
            "vscode-mit"
          ],
          "grammar": {
            "id": "vscode-source.ts",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
            "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
            "inspectedGrammarSha256": "4e92e0d7de560217d6c8d3236d85e6e17a5d77825b15729a230c761743122661",
            "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test.js",
    "family": "vscode-colorize",
    "languageId": "javascript",
    "path": "fixtures/vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test.js",
    "sha256": "d86234cda3285c0d00e0e0326f5f4d29a768e7b91dd8ce255abcf251d5afc053",
    "lane": "language-regression",
    "provenance": [
      {
        "sourceSetId": "vscode-colorize-fixtures",
        "repositoryId": "vscode",
        "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
        "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-fixtures/test.js",
        "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-fixtures/test.js",
        "licenses": [
          "vscode-mit"
        ],
        "grammar": {
          "id": "vscode-source.js",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
          "inspectedGrammarSha256": "db6f17f15bc4f5e860a3b8fa6055a69720a53df845c8d5121cdc4f128c16291f",
          "productGrammarSha256": "a2108c805865c3a1d4941b30c97bdb68b23bebd6fd22c7656d2925527cc463fb",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "source",
    "associations": [
      {
        "sourceFixtureId": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test.js",
        "format": "source",
        "provenance": {
          "sourceSetId": "vscode-colorize-fixtures",
          "repositoryId": "vscode",
          "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-fixtures/test.js",
          "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-fixtures/test.js",
          "licenses": [
            "vscode-mit"
          ],
          "grammar": {
            "id": "vscode-source.js",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
            "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
            "inspectedGrammarSha256": "db6f17f15bc4f5e860a3b8fa6055a69720a53df845c8d5121cdc4f128c16291f",
            "productGrammarSha256": "a2108c805865c3a1d4941b30c97bdb68b23bebd6fd22c7656d2925527cc463fb",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test.json",
    "family": "vscode-colorize",
    "languageId": "json",
    "path": "fixtures/vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test.json",
    "sha256": "b2d531295f4856719d5eb1bf2f5fa42bc0ea8436b5687cde0ed19e504866c360",
    "lane": "language-regression",
    "provenance": [
      {
        "sourceSetId": "vscode-colorize-fixtures",
        "repositoryId": "vscode",
        "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
        "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-fixtures/test.json",
        "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-fixtures/test.json",
        "licenses": [
          "vscode-mit"
        ],
        "grammar": {
          "id": "vscode-source.json",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "inspectedUpstreamRevision": "9bd83f1c252b375e957203f21793316203f61f70",
          "inspectedGrammarSha256": "d7238f1cc9033993b9816b0945cab4bb8ea108de0399663c551f28f913e94c70",
          "productGrammarSha256": "9381fc3b1fd0bf3aad0dde03ca4a610fe4026b42173d33d4ae7b420ff24b5989",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "source",
    "associations": [
      {
        "sourceFixtureId": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test.json",
        "format": "source",
        "provenance": {
          "sourceSetId": "vscode-colorize-fixtures",
          "repositoryId": "vscode",
          "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-fixtures/test.json",
          "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-fixtures/test.json",
          "licenses": [
            "vscode-mit"
          ],
          "grammar": {
            "id": "vscode-source.json",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
            "inspectedUpstreamRevision": "9bd83f1c252b375e957203f21793316203f61f70",
            "inspectedGrammarSha256": "d7238f1cc9033993b9816b0945cab4bb8ea108de0399663c551f28f913e94c70",
            "productGrammarSha256": "9381fc3b1fd0bf3aad0dde03ca4a610fe4026b42173d33d4ae7b420ff24b5989",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-results/test_js.json",
    "family": "vscode-colorize",
    "languageId": "javascript",
    "path": "fixtures/vscode-colorize/extensions/vscode-colorize-tests/test/colorize-results/test_js.json",
    "sha256": "1e6b893c095975b6308086eb547830e7921859b2bdb6b81fdb3f09a02b6ee43a",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "vscode-colorize-results",
        "repositoryId": "vscode",
        "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
        "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-results/test_js.json",
        "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-results/test_js.json",
        "licenses": [
          "vscode-mit"
        ],
        "grammar": {
          "id": "vscode-source.js",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
          "inspectedGrammarSha256": "db6f17f15bc4f5e860a3b8fa6055a69720a53df845c8d5121cdc4f128c16291f",
          "productGrammarSha256": "a2108c805865c3a1d4941b30c97bdb68b23bebd6fd22c7656d2925527cc463fb",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "vscode-colorize",
    "associations": [
      {
        "sourceFixtureId": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test.js",
        "format": "vscode-colorize",
        "provenance": {
          "sourceSetId": "vscode-colorize-results",
          "repositoryId": "vscode",
          "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-results/test_js.json",
          "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-results/test_js.json",
          "licenses": [
            "vscode-mit"
          ],
          "grammar": {
            "id": "vscode-source.js",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
            "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
            "inspectedGrammarSha256": "db6f17f15bc4f5e860a3b8fa6055a69720a53df845c8d5121cdc4f128c16291f",
            "productGrammarSha256": "a2108c805865c3a1d4941b30c97bdb68b23bebd6fd22c7656d2925527cc463fb",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-results/test_json.json",
    "family": "vscode-colorize",
    "languageId": "json",
    "path": "fixtures/vscode-colorize/extensions/vscode-colorize-tests/test/colorize-results/test_json.json",
    "sha256": "b5b7401ddbb3d72346defbbc46f518bb9f5ae9e3a623dcb0c49c06445117fc8d",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "vscode-colorize-results",
        "repositoryId": "vscode",
        "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
        "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-results/test_json.json",
        "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-results/test_json.json",
        "licenses": [
          "vscode-mit"
        ],
        "grammar": {
          "id": "vscode-source.json",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "inspectedUpstreamRevision": "9bd83f1c252b375e957203f21793316203f61f70",
          "inspectedGrammarSha256": "d7238f1cc9033993b9816b0945cab4bb8ea108de0399663c551f28f913e94c70",
          "productGrammarSha256": "9381fc3b1fd0bf3aad0dde03ca4a610fe4026b42173d33d4ae7b420ff24b5989",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "vscode-colorize",
    "associations": [
      {
        "sourceFixtureId": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test.json",
        "format": "vscode-colorize",
        "provenance": {
          "sourceSetId": "vscode-colorize-results",
          "repositoryId": "vscode",
          "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-results/test_json.json",
          "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-results/test_json.json",
          "licenses": [
            "vscode-mit"
          ],
          "grammar": {
            "id": "vscode-source.json",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
            "inspectedUpstreamRevision": "9bd83f1c252b375e957203f21793316203f61f70",
            "inspectedGrammarSha256": "d7238f1cc9033993b9816b0945cab4bb8ea108de0399663c551f28f913e94c70",
            "productGrammarSha256": "9381fc3b1fd0bf3aad0dde03ca4a610fe4026b42173d33d4ae7b420ff24b5989",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-results/test-brackets_tsx.json",
    "family": "vscode-colorize",
    "languageId": "tsx",
    "path": "fixtures/vscode-colorize/extensions/vscode-colorize-tests/test/colorize-results/test-brackets_tsx.json",
    "sha256": "aca259963a00993ce3794d8d5efd8b7b6668f24c81127f587b26057c280b3c3e",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "vscode-colorize-results",
        "repositoryId": "vscode",
        "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
        "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-results/test-brackets_tsx.json",
        "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-results/test-brackets_tsx.json",
        "licenses": [
          "vscode-mit"
        ],
        "grammar": {
          "id": "vscode-source.tsx",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
          "inspectedGrammarSha256": "532fb887df3117e9f4eaf5d3ea1e850114fb6899fe3d3ddabedb153bec08b32a",
          "productGrammarSha256": "e04ffdb50f237b70ab8c27653681a72004617ece8a6d5ff6aba58eaae6082eae",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "vscode-colorize",
    "associations": [
      {
        "sourceFixtureId": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test-brackets.tsx",
        "format": "vscode-colorize",
        "provenance": {
          "sourceSetId": "vscode-colorize-results",
          "repositoryId": "vscode",
          "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-results/test-brackets_tsx.json",
          "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-results/test-brackets_tsx.json",
          "licenses": [
            "vscode-mit"
          ],
          "grammar": {
            "id": "vscode-source.tsx",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
            "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
            "inspectedGrammarSha256": "532fb887df3117e9f4eaf5d3ea1e850114fb6899fe3d3ddabedb153bec08b32a",
            "productGrammarSha256": "e04ffdb50f237b70ab8c27653681a72004617ece8a6d5ff6aba58eaae6082eae",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-results/test-keywords_ts.json",
    "family": "vscode-colorize",
    "languageId": "typescript",
    "path": "fixtures/vscode-colorize/extensions/vscode-colorize-tests/test/colorize-results/test-keywords_ts.json",
    "sha256": "5c6f223454f3341775dafc79a5d22d1f55518b4cbe1c9787b946ae0021e39bd2",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "vscode-colorize-results",
        "repositoryId": "vscode",
        "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
        "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-results/test-keywords_ts.json",
        "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-results/test-keywords_ts.json",
        "licenses": [
          "vscode-mit"
        ],
        "grammar": {
          "id": "vscode-source.ts",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
          "inspectedGrammarSha256": "4e92e0d7de560217d6c8d3236d85e6e17a5d77825b15729a230c761743122661",
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "vscode-colorize",
    "associations": [
      {
        "sourceFixtureId": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test-keywords.ts",
        "format": "vscode-colorize",
        "provenance": {
          "sourceSetId": "vscode-colorize-results",
          "repositoryId": "vscode",
          "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-results/test-keywords_ts.json",
          "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-results/test-keywords_ts.json",
          "licenses": [
            "vscode-mit"
          ],
          "grammar": {
            "id": "vscode-source.ts",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
            "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
            "inspectedGrammarSha256": "4e92e0d7de560217d6c8d3236d85e6e17a5d77825b15729a230c761743122661",
            "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-results/test-object-literals_ts.json",
    "family": "vscode-colorize",
    "languageId": "typescript",
    "path": "fixtures/vscode-colorize/extensions/vscode-colorize-tests/test/colorize-results/test-object-literals_ts.json",
    "sha256": "0e9025351d57423af73ba0d72232ec1867e174ecf6c5ff2e27c2f21cd686e36b",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "vscode-colorize-results",
        "repositoryId": "vscode",
        "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
        "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-results/test-object-literals_ts.json",
        "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-results/test-object-literals_ts.json",
        "licenses": [
          "vscode-mit"
        ],
        "grammar": {
          "id": "vscode-source.ts",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
          "inspectedGrammarSha256": "4e92e0d7de560217d6c8d3236d85e6e17a5d77825b15729a230c761743122661",
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "vscode-colorize",
    "associations": [
      {
        "sourceFixtureId": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test-object-literals.ts",
        "format": "vscode-colorize",
        "provenance": {
          "sourceSetId": "vscode-colorize-results",
          "repositoryId": "vscode",
          "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-results/test-object-literals_ts.json",
          "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-results/test-object-literals_ts.json",
          "licenses": [
            "vscode-mit"
          ],
          "grammar": {
            "id": "vscode-source.ts",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
            "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
            "inspectedGrammarSha256": "4e92e0d7de560217d6c8d3236d85e6e17a5d77825b15729a230c761743122661",
            "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-tree-sitter-results/test-keywords_ts.json",
    "family": "vscode-colorize",
    "languageId": "typescript",
    "path": "fixtures/vscode-colorize/extensions/vscode-colorize-tests/test/colorize-tree-sitter-results/test-keywords_ts.json",
    "sha256": "107372c95b5195e38871abb9e71d8fe8ef55895587a1837a7c37848b3a5b42d8",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "vscode-colorize-tree-sitter-results",
        "repositoryId": "vscode",
        "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
        "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-tree-sitter-results/test-keywords_ts.json",
        "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-tree-sitter-results/test-keywords_ts.json",
        "licenses": [
          "vscode-mit"
        ],
        "grammar": {
          "id": "vscode-source.ts",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
          "inspectedGrammarSha256": "4e92e0d7de560217d6c8d3236d85e6e17a5d77825b15729a230c761743122661",
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "vscode-tree-sitter-capture",
    "associations": [
      {
        "sourceFixtureId": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test-keywords.ts",
        "format": "vscode-tree-sitter-capture",
        "provenance": {
          "sourceSetId": "vscode-colorize-tree-sitter-results",
          "repositoryId": "vscode",
          "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-tree-sitter-results/test-keywords_ts.json",
          "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-tree-sitter-results/test-keywords_ts.json",
          "licenses": [
            "vscode-mit"
          ],
          "grammar": {
            "id": "vscode-source.ts",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
            "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
            "inspectedGrammarSha256": "4e92e0d7de560217d6c8d3236d85e6e17a5d77825b15729a230c761743122661",
            "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  },
  {
    "id": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-tree-sitter-results/test-object-literals_ts.json",
    "family": "vscode-colorize",
    "languageId": "typescript",
    "path": "fixtures/vscode-colorize/extensions/vscode-colorize-tests/test/colorize-tree-sitter-results/test-object-literals_ts.json",
    "sha256": "dc3e873a718dd1b60f162930dcff1b30568da7d4cc4e64b84245a1bf132c9fa7",
    "lane": "annotated-expectation",
    "provenance": [
      {
        "sourceSetId": "vscode-colorize-tree-sitter-results",
        "repositoryId": "vscode",
        "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
        "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-tree-sitter-results/test-object-literals_ts.json",
        "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-tree-sitter-results/test-object-literals_ts.json",
        "licenses": [
          "vscode-mit"
        ],
        "grammar": {
          "id": "vscode-source.ts",
          "generatedAgainstRevision": null,
          "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
          "inspectedGrammarSha256": "4e92e0d7de560217d6c8d3236d85e6e17a5d77825b15729a230c761743122661",
          "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
          "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
          "productPackage": "@shikijs/langs@4.4.3"
        }
      }
    ],
    "split": "development",
    "format": "vscode-tree-sitter-capture",
    "associations": [
      {
        "sourceFixtureId": "vscode-colorize/extensions/vscode-colorize-tests/test/colorize-fixtures/test-object-literals.ts",
        "format": "vscode-tree-sitter-capture",
        "provenance": {
          "sourceSetId": "vscode-colorize-tree-sitter-results",
          "repositoryId": "vscode",
          "revision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
          "upstreamPath": "extensions/vscode-colorize-tests/test/colorize-tree-sitter-results/test-object-literals_ts.json",
          "manifestFileId": "vscode:extensions/vscode-colorize-tests/test/colorize-tree-sitter-results/test-object-literals_ts.json",
          "licenses": [
            "vscode-mit"
          ],
          "grammar": {
            "id": "vscode-source.ts",
            "generatedAgainstRevision": null,
            "inspectedCheckoutRevision": "5470377e71f72089f2bbd5eb8aeb862892f78b31",
            "inspectedUpstreamRevision": "48f608692aa6d6ad7bd65b478187906c798234a8",
            "inspectedGrammarSha256": "4e92e0d7de560217d6c8d3236d85e6e17a5d77825b15729a230c761743122661",
            "productGrammarSha256": "c131a59a924cda308e7110ca829803fa2bfd04688f6bc1c809285c4a583e25cc",
            "productRevision": "7f0dfc9e29fa9e3ee90c981147f77f6fcb656481",
            "productPackage": "@shikijs/langs@4.4.3"
          }
        }
      }
    ]
  }
]
